/**
 * This file is generated by generate-i18n.mjs
 * Do not edit this file directly
 */
import type enMessage from '../locales/en/messages.json';
import type esMessage from '../locales/es/messages.json';

export type MessageKey = keyof typeof enMessage & keyof typeof esMessage;

export type DevLocale = 'en' | 'es';
